### ISSUE TITLE
Failed Heartbeat after a while

### ISSUE THREAD

**Issue by Demuos** [jkcoxson/netmuxd#14] opened 2022-07-14 14:28 UTC
I´m trying to automatically backup my iPhone 11 to my ubuntu 22.04 Server NAS via Wifi, but idevicebackup2 doesn´t find my device on wlan. 
```shell
dom@server:~$ idevicebackup2 backup --full . -n
No device found.
```
usbmuxd and netmuxd are started but looking at the logs I can see that Heartbeat fails after a while and the device is added again.
I´m using the latests release of netmuxd.
```shell
[2022-07-14T09:27:02Z INFO  netmuxd::heartbeat] Heartbeat failed for 00008030-xxx
[2022-07-14T09:27:02Z INFO  netmuxd::heartbeat] Removing device 00008030-xxx from muxer
[2022-07-14T09:27:02Z INFO  netmuxd::central_data] Removing device: "00008030-xxx"
[2022-07-14T09:27:02Z INFO  rusty_libimobiledevice::services::heartbeat] Dropping heartbeat client
[2022-07-14T09:27:02Z INFO  rusty_libimobiledevice::idevice] Dropping device 00008030-xxx
```
(UDID removed)

full log `sudo RUST_LOG=trace ./netmuxd —disable-unix —host 127.0.0.1`:
[https://gist.github.com/Demuos/c23ca9bb505701fa28436ec36136eb22](https://gist.github.com/Demuos/c23ca9bb505701fa28436ec36136eb22)

I would appreciate any help :)

**Comment by jkcoxson** [comment] 2022-07-15 08:02
I need to fine-tune the delay between heartbeats, the device is chopping the connection due to unexpected packet intervals. This is a duplicate of #10 though, so I will close this in favor of it.

**Closed by jkcoxson** 2022-07-15 08:02 UTC
